version: '3'

services:
    db:
        container_name: database
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: my-secret-pw
            MYSQL_DATABASE: streaming
        ports:
            - 3306
        volumes:
            - db-data:/var/lib/mysql

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin:latest
        restart: always
        ports:
            - 8001:80
        environment:
            - PMA_HOST=db

    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8080

volumes:
    db-data: