version: "3.7"

services:
  mysql:
    image: mysql
    networks:
      - my-network
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw

  # phpMyAdmin container
  phpmyadmin:
    image: phpmyadmin
    networks:
      - my-network
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

networks:
  my-network:
      